services:
  api:
    image: csc131/ga
    container_name: ga-api
    build: .
    environment:
        - spring.profiles.active=test      
    depends_on:
      - db    
    ports:
      - "8080:8080"
  db:
    image: mongo
    container_name: ga-db
    restart: always
    ports:
      - "27017:27017" 
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
